version: '3'
services:
   db:
    image: postgres:alpine
    restart: always
    ports:
      - 5432:5432
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: KION
      POSTGRES_USER: root
      POSTGRES_PASSWORD: Root123
    container_name: db
   api:
    build: .
    ports:
      - 5000:5000
    environment:
      SECRET: secret
      FFMPEG: ffmpeg
      PORT: 5000
      DATABASE_URL: 'postgresql://root:Root123@db:5432/KION'
    volumes:
      - api-static:/app/static
    depends_on:
      - db
    restart:
      on-failure
    container_name: api
volumes:
  db-data:
  api-static:
