version: '3'
services:
   db:
    image: postgres:alpine
    restart: always
    ports:
      - 5432:5432
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: KION
      POSTGRES_USER: root
      POSTGRES_PASSWORD: Root123
    container_name: db
   server:
    build: .
    ports:
      - 5000:5000
    environment:
      DB_NAME: KION
      DB_USER: root
      DB_PASSWORD: Root123
      SECRET: secret
      DB_PORT: 5432
      DB_HOST: db
      FFMPEG: ffmpeg
    volumes:
      - server-assets:/server/assets
    depends_on:
      - db
    restart:
      on-failure
    container_name: api
volumes:
  db-data:
  server-assets:
