/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "N-110091-g261fb55e39-20230326"
#endif /* AVUTIL_FFVERSION_H */
